import {Poppins} from "next/font/google";
import "./globals.css";
import 'animate.css';
import { ToastContainer } from "react-toastify";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";


const PoppinsFont = Poppins({
variable:"--font-poppins",
subsets:["latin"],
weight:["400", "500", "600", "700", "800"]
});

export const metadata = {
  title: "Mango",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${PoppinsFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Navbar></Navbar>
       <main>
         {children}
         <ToastContainer></ToastContainer>
       </main>
       <Footer></Footer>
        </body>
    </html>
  );
}
